#! /bin/sh
#
# Helper to launch the celery worker

APP_NAME=pantos-service-node
APP_DIR=/opt/pantos/"$APP_NAME"
export PYTHONHOME=$APP_DIR
export PATH=$APP_DIR/bin:$PATH
export PYTHONUNBUFFERED=1

source_if_not_set() {
    [ ! -f "$1" ] && return
    echo "Sourcing $1"
    while IFS= read -r line || [ -n "$line" ]; do
        [ -z "$line" ] || [ "${line#\#}" != "$line" ] && continue
        key="${line%%=*}"
        eval currentValue=\$$key
        [ -n "$currentValue" ] && continue
        export "$line"
    done < "$1"
}

source_if_not_set /etc/default/"$APP_NAME"
if [ -f "$PANTOS_ENV_FILE" ]; then
    source_if_not_set "$PANTOS_ENV_FILE"
fi

cd "$APP_DIR"

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      echo "Usage: $0 [-h|--help] [-s|--status]"
      echo "-h, --help   Show this help message"
      echo "-s, --status Start the celery worker with status monitoring"
      exit 0
      ;;
    -s|--status)
      echo "Querying the status of the celery worker"
      exec ./bin/python -m celery -A pantos.servicenode inspect ping -d celery@$HOSTNAME
      exit $?
      ;;
    *)
      break
      ;;
  esac
done

exec ./bin/python -m celery -A pantos.servicenode worker --uid $(id -u "$APP_NAME") --gid $(id -g "$APP_NAME") -l INFO -n pantos.servicenode -Q transfers,bids
